import React, {useEffect, useState} from 'react';
import {Check, ChevronRight, Cpu, Mail, Mic, Send, ShieldCheck, Sparkles, Volume2} from 'lucide-react';
import {api} from './api';

export function SetupWizard({config,status,desktop,models,onSave,onProvider,onModel,onConnections,onDesktop,onTestVoice,onFinish,suspended}:{config:any;status:any;desktop:any;models:string[];onSave:(c:any)=>Promise<void>;onProvider:(p:string)=>Promise<void>;onModel:(m:string)=>Promise<void>;onConnections:()=>void;onDesktop:()=>Promise<void>;onTestVoice:()=>Promise<void>;onFinish:()=>Promise<void>;suspended:boolean}) {
  const [step,setStep]=useState(0),[name,setName]=useState(config.display_name||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[audio,setAudio]=useState<any>(null);
  useEffect(()=>{api('/audio/devices').then(setAudio).catch(()=>setAudio(null));},[]);
  async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const titles=['Welcome to your orbit.','Choose your intelligence.','Give Jarvis a voice.','Connect your world.'];
  return <div className="modal-overlay wizard-overlay" style={suspended?{display:'none'}:undefined}><div className="modal setup-wizard" role="dialog" aria-modal="true" aria-labelledby="wizard-title">
    <div className="wizard-logo"><Sparkles size={29}/><span>JARVIS <small>FIRST CONTACT</small></span></div>
    <div className="wizard-progress" aria-label={`Setup step ${step+1} of 4`}>{titles.map((_,i)=><i key={i} className={i<=step?'complete':''}/>)}</div>
    <div className="eyebrow">SYSTEM INITIALIZATION / 0{step+1}</div><h2 id="wizard-title">{titles[step]}</h2>
    {step===0&&<div className="wizard-content"><p>Your personal assistant, powered by your choice of model. Every spoken reply uses local Kokoro. Speech recognition uses local Whisper.</p><label>What should Jarvis call you?<input autoFocus autoComplete="given-name" maxLength={60} placeholder="Your name (optional)" value={name} onChange={e=>setName(e.target.value)}/></label><div className="wizard-note"><ShieldCheck size={18}/><span>Credentials are saved privately on this machine. Each coworker connects their own accounts.</span></div><p className="helper">The computer must remain awake. Desktop listening can continue when the browser is closed, after you enable it.</p></div>}
    {step===1&&<div className="wizard-content"><p>Switch engines anytime in the dashboard. Local Ollama chat can work offline after its model is installed.</p><div className="provider-switch"><button disabled={busy} className={config.provider==='ollama'?'on':''} onClick={()=>void run(()=>onProvider('ollama'))}><Cpu size={16}/>Ollama · local</button><button disabled={busy} className={config.provider==='openai'?'on':''} onClick={()=>void run(()=>onProvider('openai'))}><Sparkles size={16}/>OpenAI</button></div><label>Model<select value={config.model} disabled={busy || !models.length} onChange={e=>void run(()=>onModel(e.target.value))}><option value="">Choose a model</option>{models.map(m=><option key={m} value={m}>{m}</option>)}</select></label><p className="helper">{config.provider==='openai'?(config.openai_configured?'OpenAI key configured.':'Add your own API key to load models. API calls are billed to your account.'):(status?.ollama.connected?'Ollama is responding. All installed chat models appear here.':'Ollama is unavailable. Run the launcher again or use OpenAI.')}</p><button className="outline-button" onClick={onConnections}>Configure accounts</button>{!config.model&&<p className="helper">You can continue and select a model later. Chat requires an available model.</p>}</div>}
    {step===2&&<div className="wizard-content"><div className="wizard-status"><span>Kokoro synthesis</span><b>{status?.voice.tts?'Ready':status?.voice.loading?'Loading…':'Needs setup'}</b></div><div className="wizard-status"><span>Whisper recognition</span><b>{status?.voice.stt?'Ready':status?.voice.loading?'Loading…':'Needs setup'}</b></div><div className="button-row"><button className="outline-button" disabled={busy || !status?.voice.tts || desktop.enabled} onClick={()=>void run(onTestVoice)}><Volume2 size={15}/>Test voice</button><button className="primary-button" disabled={busy || !status?.voice.stt || !status?.voice.tts || !config.model} onClick={()=>void run(onDesktop)}><Mic size={15}/>{desktop.enabled?'Pause listening':'Enable desktop listening'}</button></div><div className="wizard-meter" aria-label="Live microphone level"><i style={{width:Math.min(100,(desktop.level||0)*100)+'%'}}/></div><p className="helper">{desktop.enabled?'Listening is enabled. Say “Jarvis, tell me the time.”':'Listening begins only after you enable it and grant microphone access.'}</p><p className="helper">Default microphone: {audio?.devices?.[audio?.default_input]?.name||'Select an input device in system Sound settings'}. Choose your microphone and speakers in Windows/macOS Sound settings.</p><p className="helper">On macOS, allow Terminal/Python in Privacy & Security → Microphone. On Windows, enable microphone access for desktop apps in Privacy settings. You can skip this step and type instead.</p></div>}
    {step===3&&<div className="wizard-content"><p>These connections are optional. Their indicators turn green only after the backend verifies access.</p><div className="wizard-status"><span><Mail size={17}/>Gmail</span><b>{status?.gmail.connected?'Connected':'Not connected'}</b></div><div className="wizard-status"><span><Send size={17}/>Telegram</span><b>{status?.telegram.connected?'Connected':'Not connected'}</b></div><button className="primary-button" onClick={onConnections}>Connect Gmail / Telegram</button><p className="helper">Gmail requires your Google OAuth client and browser consent. Telegram requires your dedicated bot token and private chat ID. Automatic Telegram replies are opt-in.</p><p className="helper">If you choose OpenAI, requests and any inbox context you ask Jarvis to use are sent to OpenAI. Local Ollama keeps inference on this computer.</p></div>}
    {error&&<div className="error-banner" role="alert">{error}</div>}
    <div className="wizard-footer"><button className="outline-button" disabled={busy || step===0} onClick={()=>setStep(step-1)}>Back</button><span>0{step+1} / 04</span><button className="primary-button" disabled={busy} onClick={()=>void run(async()=>{if(step===0)await onSave({display_name:name.trim()});if(step<3)setStep(step+1);else await onFinish();})}>{busy?'Working…':step===3?'Enter command center':'Continue'}{step===3?<Check size={15}/>:<ChevronRight size={15}/>}</button></div>
  </div></div>;
}
